version: "3.9"
services:
  # API micro-service
  service.apimicro:
    container_name: micro_api
    hostname: micro_api
#    build:
#      context: ./_dockerfiles
#      dockerfile: dockerfile.micro_api
#    image: micro_api:local
    image: registry.bokchi.com/micro_api:0.10.0-community-snapshot
    user: ${BOKCHI_ID}
    environment:
      mode: "comm"
    env_file:
      - ./env/service.env
    deploy:
      resources:
        limits:
          memory: 1g
    volumes:
      - ./_logs:/micro/service/apimicro/_logs
    ports:
      - 9011:9011

  # User micro-service
  service.usermicro:
    container_name: micro_user
    hostname: micro_user
    image: registry.bokchi.com/micro_user:0.10.0-community-snapshot
    user: ${BOKCHI_ID}
    environment:
      mode: "comm"
    env_file:
      - ./env/service.env
    deploy:
      resources:
        limits:
          memory: 1g
    volumes:
      - ./_logs:/micro/service/usermicro/_logs
    ports:
      - 9021:9021

  # Experiment micro-service
  service.expermicro:
    container_name: micro_experiment
    hostname: micro_experiment
    image: registry.bokchi.com/micro_experiment:0.10.0-community-snapshot
    user: ${BOKCHI_ID}
    environment:
      mode: "comm"
    env_file:
      - ./env/service.env
    deploy:
      resources:
        limits:
          memory: 1g
    volumes:
      - ./_logs:/micro/service/expermicro/_logs
    ports:
      - 9031:9031

  # Message micro-service
  service.mesgmicro:
    container_name: micro_message
    hostname: micro_message
    image: registry.bokchi.com/micro_message:0.10.0-community-snapshot
    user: ${BOKCHI_ID}
    environment:
      mode: "comm"
    env_file:
      - ./env/service.env
    deploy:
      resources:
        limits:
          memory: 1g
    volumes:
      - ./_logs:/micro/service/mesgmicro/_logs
    ports:
      - 9041:9041

  # Resource micro-service
  service.resormicro:
    container_name: micro_resource
    hostname: micro_resource
    image: registry.bokchi.com/micro_resource:0.10.0-community-snapshot
    user: ${BOKCHI_ID}
    environment:
      mode: "comm"
    env_file:
      - ./env/service.env
    deploy:
      resources:
        limits:
          memory: 1g
    volumes:
      - ./_logs:/micro/service/resormicro/_logs
      - ./storage/fs:/micro/storage
      - ./storage/.ssh:/home/bokchi/.ssh
    ports:
      - 9051:9051
      - 19051:19051

  # Dashboard publisher
  publisher.board:
    container_name: publisher_board
    hostname: publisher_board
    image: registry.bokchi.com/publisher_board:0.10.0-community-snapshot
#    user: ${BOKCHI_ID}
    environment:
      mode: "comm"
    env_file:
      - ./env/publisher.env
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - 9111:9111







  

