# bokchi ----
# for application

# rdb
RDB_URL: ENC(CCj4a3a+CvRhYctjCUsbgBbKaHxOa4oqpuw8mp4YpaAOh69plXKKD85dNkNSOmdNnMyHSHv2TM8=)
RDB_USR: ENC(QP3qfRU3VIr7H5Et8C4PTSDJURPKsSvS)
RDB_PW: ENC(ovUJvz0nbXl81u19yViHyks/oT4k0vMV73F/5PrBQKw=)

#
spring:
  datasource:
    url: ${RDB_URL}
    username: ${RDB_USR}
    password: ${RDB_PW}
